config/routes.rb
MendeleyRepo::Application.routes.draw do
  root :to => "home#index"
  resources :users
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin
  
end

app/models/drive_file.rb
class DriveFile
  include Mongoid::Document
  
  field :file_hash, type: String
  field :drive_uuid, type: String  
  field :drive_url, type: String
  
  validates(:file_hash, :presence => true)
  validates(:drive_uuid, :presence => true)
  
  
end

app/models/item.rb
require 'citeproc'
class Item
  include Mongoid::Document
  
  field :mendeley_metadata, type: Hash
  field :mendeley_version, type: Time
  field :mendeley_id, type: String
  field :mendeley_group_id, type: String
  field :mendeley_canonical_id, type: String
  
  has_and_belongs_to_many :users
  embeds_many :drive_files do
    def find_by_file_hash(file_hash)
      where( file_hash: file_hash).first
    end
  end
  
  validates(:mendeley_id, :presence => true)
  validates(:mendeley_metadata, :presence => true)
  validates(:mendeley_version, :presence => true)
  
  after_validation do |item|
    item.mendeley_canonical_id = item.mendeley_metadata["canonical_id"]
  end
  
  
  
  # right now only allowing one pdf / record. will update later.
  # optional values of position index for files, which alls the document title to reflex the order of the file. 
  def to_drive_metadata(position = 1, number_of_files = 1 ) 
    title = "#{self.mendeley_metadata["title"][0..100]} -- (#{position}/#{number_of_files})" 
    { :title => title, :description => self.to_bibtex.to_s }
  end
  
  def to_bibtex
    BibtexConverter.process(self.mendeley_metadata)
  end
  
  def to_apa
    CiteProc.process self.to_bibtex.to_citeproc, :style => :apa
  end
  
  

end

app/models/sync_folder.rb
class SyncFolder
  include Mongoid::Document
  
  field :folder_id, type: String
  field :parent_group, type: String # for folders that are part of a group
  
  validates_uniqueness_of :folder_id
  
  def to_params
    folder_id
  end
    
  
  
end

app/models/user.rb
require 'open-uri'

class User
  include Mongoid::Document
  attr_protected :provider, :uid, :name, :email
  
  field :provider, type: String
  field :uid, type: String
  field :name, type: String
  field :email, type: String
  field :token, type: String
  field :secret, type: String
  field :ingest_folder, type: String
  field :sync_folders, type: Array, :default => []
  
 # embeds_many :sync_folders 
#  accepts_nested_attributes_for :sync_folders, allow_destroy: true
  
  has_and_belongs_to_many :items
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || "UNKNOWN USER #{rand(100)}"
         user.email = auth['info']['email'] || ""
         user.uid = auth["uid"]  
         user.token = auth['credentials']['token']
         user.secret = auth['credentials']['secret']
      end
      user.ingest_folder = GoogleDrive.new.create_user_ingest_folder(user.name)
    end
  end
  
  def show_folders
    return mendeley.get('/oapi/library/folders/')
  end
  
  def show_folder_items(folder_id, page = "0")
    if folder_id.include?(":") # group folders have the group id prefixed. 
      group_id, folder_id = folder_id.split(":")
      return mendeley.get("/oapi/library/groups/#{group_id}/folders/#{folder_id}?page=#{page}")
    else
      return mendeley.get("/oapi/library/folders/#{folder_id}?page=#{page}")
    end
  end
  
  def show_document_details(document_id, group_id = nil)
    if group_id
      return mendeley.get("/oapi/library/groups/#{group_id}/#{document_id}")
    else
      return mendeley.get("/oapi/library/documents/#{document_id}")
    end
  end
  
  def show_library
    return mendeley.get('/oapi/library')
  end
  
  def show_groups
    groups = mendeley.get('/oapi/library/groups')
    groups.each { |group| group["folders"] = show_group_collections(group["id"]) }
    groups
  end

  def show_group_collections(group_id)
    mendeley.get("/oapi/library/groups/#{group_id}/folders")
  end
  
  def download_document(document_id, file_hash, group_id = nil)
     if group_id
         return mendeley.download("/oapi/library/documents/#{document_id}/file/#{file_hash}/#{group_id}")
      else
        return mendeley.download("/oapi/library/documents/#{document_id}/file/#{file_hash}")
      end
  end
  
  def self.sync_all_folders
    User.all.each do |user|
      puts "Syncing User: #{user.id}"
      user.sync_folders.each do |folder| 
        puts "Syncing Folder: #{folder}"
        FolderSync.process(user, folder)
      end
    end
  end
  
  protected
  
  def mendeley
    Mendeley.new(self.token, self.secret)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery

    helper_method :current_user
    helper_method :user_signed_in?
    helper_method :correct_user?

    private
      def current_user
        begin
          @current_user ||= User.find(session[:user_id]) if session[:user_id]
        rescue Mongoid::Errors::DocumentNotFound
          nil
        end
      end

      def user_signed_in?
        return true if current_user
      end

      def correct_user?
        @user = User.find(params[:id])
        unless current_user == @user
          redirect_to root_url, :alert => "Access denied."
        end
      end

      def authenticate_user!
        if !current_user
          redirect_to root_url, :alert => 'You need to sign in for access to this page.'
        end
      end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to user_path(user), :notice => "Signed in!"
  end
  
  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end
  
  def new
    redirect_to '/auth/mendeley'
  end
  
  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   respond_to :html, :json
  def show
     @user = User.find(params[:id])
     @items = @user.items.paginate :page => params[:page], :per_page => 20
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
      @user = User.find(params[:id])
      if @user.update_attributes(params[:user])  
        flash[:notice] = "Successfully updated user."  
      end  
      respond_with(@user)  
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper



  def group_list(groups)
    content_tag :ul, :class => "name nav-list" do
     groups.map do |group|
       content_tag(:li, group["name"]) +
       folder_list(group["folders"], group["id"]) 
     end.join("").html_safe  
    end
  end
  
  def folder_list(list, group_id = nil)
    content_tag :ul, :class => "name nav-list" do
      list.map do |folder|
        id = folder_id(folder["id"], group_id)
        content_tag(:li) do
          content_tag(:label, folder["name"], :class => "checkbox inline") <<             
            check_box_tag( "sync_folders_#{id.gsub(":", "_")}" , id, @user.sync_folders.include?(id), :name => "user[sync_folders][]", :class => "sync_folders" ) 
        end.html_safe
      end.join("").html_safe
    end.html_safe
  end
    
  def folder_id(id, group_id)
    group_id ? "#{group_id}:#{id}" : id
  end


end

app/views/items/_item.html.haml
= item.to_apa
- item.drive_files.each do |file|
  = link_to(content_tag("i", "", :class => "icon-file" ), file.drive_url)

%br 
%br

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "MendeleyRepo"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    =# %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") WMU Library Repository
          .container.nav-collapse
            %ul.nav
              %li= link_to "Sign In", signin_path
              %li= link_to "Sign Out", signout_path

    .container-fluid

      = yield
    
      %footer
        %p &copy; WMU 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), @user, :class => 'btn'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:_id)
      %th= model_class.human_attribute_name(:provider)
      %th= model_class.human_attribute_name(:uid)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user._id
        %td= user.provider
        %td= user.uid
        %td= user.name
        %td= user.email
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.row-fluid
  .span3
    .well.sidebar-nav
      = form_for @user do |user_form|
        %h4 Group Folders
        = group_list(@user.show_groups)
        %h4 User Folders
        = folder_list(@user.show_folders)
        = user_form.submit "Update Folders", :class => "sync_folders btn btn-info"
  .span9
    = bootstrap_flash
    .page-header
      %h1
        =t '.title', :default => @user.name
        = link_to "Edit My Profile", edit_user_path(@user), :class => 'btn btn-link'

    %p
      #items
        - @items.each do |item|
          = render item
  .paginate
    = will_paginate @items
  

app/views/users/show.js.erb
$('#items').append('<%= j render(@items) %>');
<% if @items.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@items) %>');
<% else %>
  $('.pagination').remove();
<% end %>